#!/bin/bash
# Stage Data/ for the re-evaluation sweep without re-downloading anything.
#
# Heavy immutable assets (images, archives, synthetic sets) are symlinked from the
# old GenDataTraining checkout. The COCO JSONs and YOLO label directories for the
# four evaluation datasets are REGENERATED with this repo's fixed converters, so
# the old repo's Data/ is never written to and stays intact as the provenance
# record for the currently published tables.
#
# Usage:  ./stage_data_from_old_repo.sh [/path/to/GenDataTraining]
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OLD="${1:-$(dirname "$REPO")/GenDataTraining}"
SRC="$OLD/Data"
DST="$REPO/Data"

[ -d "$SRC" ] || { echo "ERROR: old Data/ not found at $SRC" >&2; exit 1; }
echo "Staging from : $SRC"
echo "Staging into : $DST"

mkdir -p "$DST"

# --- 1. Datasets used verbatim (no converter changes) -> whole-tree symlinks ----
for d in ClearRealSubset GeminiAugmented AutomoldAugmented full_bdd_train; do
    if [ -e "$SRC/$d" ] && [ ! -e "$DST/$d" ]; then
        ln -s "$SRC/$d" "$DST/$d"
        echo "  symlink  $d"
    fi
done

# --- 2. Eval datasets: symlink the imagery, regenerate annotations -------------
# BDD100K val: images and YOLO .txt labels are unchanged, so they are symlinked.
#
# The COCO json is NOT rebuilt from the DatasetNinja val/ann source: those
# annotations store integer-quantized corners, whereas the published
# bdd100k_val_coco.json carries sub-pixel float boxes. Regenerating would coarsen
# the ground truth and make val/* incomparable to the published numbers. Instead
# the existing json is carried over with annotation ids shifted +1, which is
# exactly what the converter's annotation_id fix does and provably leaves every
# box, class, and image untouched.
mkdir -p "$DST/bdd100k_val"
for sub in images labels; do
    [ -e "$DST/bdd100k_val/$sub" ] || ln -s "$SRC/bdd100k_val/$sub" "$DST/bdd100k_val/$sub"
done

# DAWN: raw imagery symlinked, COCO + YOLO labels regenerated by this repo.
mkdir -p "$DST/DAWN"
[ -e "$DST/DAWN/DAWN" ] || ln -s "$SRC/DAWN/DAWN" "$DST/DAWN/DAWN"

# Foggy Zurich: raw imagery symlinked, COCO + YOLO labels regenerated.
mkdir -p "$DST/FoggyZurich"
[ -e "$DST/FoggyZurich/Foggy_Driving" ] || ln -s "$SRC/FoggyZurich/Foggy_Driving" "$DST/FoggyZurich/Foggy_Driving"

# ACDC: extracted imagery symlinked, COCO + YOLO labels regenerated. The
# registration-gated archives + extracted gt_detection/ come from the old repo,
# so preprocess_acdc.py finds them where it expects and skips re-extraction.
mkdir -p "$DST/ACDC"
[ -e "$DST/ACDC/rgb_anon" ] || ln -s "$SRC/ACDC/rgb_anon" "$DST/ACDC/rgb_anon"
[ -e "$REPO/dataset_utils/acdc_dataset_zip_files" ] || \
    ln -s "$OLD/dataset_utils/acdc_dataset_zip_files" "$REPO/dataset_utils/acdc_dataset_zip_files"

echo
echo "Regenerating annotations with this repo's converters..."
cd "$REPO"
python dataset_utils/convert_dawn_to_coco.py
python dataset_utils/preprocess_foggy_zurich.py
python dataset_utils/preprocess_acdc.py

python - "$SRC/bdd100k_val/bdd100k_val_coco.json" "$DST/bdd100k_val/bdd100k_val_coco.json" <<'PY'
import json, sys
src, dst = sys.argv[1], sys.argv[2]
d = json.load(open(src))
shift = 1 - min(a["id"] for a in d["annotations"])
if shift:
    for a in d["annotations"]:
        a["id"] += shift
json.dump(d, open(dst, "w"))
print(f"BDD100K val: carried over {len(d['annotations'])} annotations, "
      f"annotation ids shifted by {shift} (boxes untouched)")
PY

# --- 3. Checkpoints: read-only symlink to the old runs/ ------------------------
[ -e "$REPO/runs" ] || { ln -s "$OLD/runs" "$REPO/runs"; echo "  symlink  runs -> $OLD/runs"; }

# --- 4. YOLO temp datasets ----------------------------------------------------
# The BDD100K per-weather pass validates against each run's own mixed training
# set. Those were already built during training, so reuse them instead of
# recopying ~30k images per run. Only train/ and val/ are linked; data.yaml and
# validation_sets/ are written locally, so evaluation never writes into the old
# checkout. Staging these up front also stops concurrent shards of the same run
# from each trying to build the directory and clobbering one another.
OLD_TEMP="$OLD/local/yolo_dataset"
if [ -d "$OLD_TEMP" ]; then
    echo
    echo "Linking prebuilt YOLO temp datasets..."
    staged=0
    for src in "$OLD_TEMP"/*/; do
        run=$(basename "$src")
        [ -d "$src/train/images" ] || { echo "  skip $run (no train/images)"; continue; }
        dst="$REPO/local/yolo_dataset/$run"
        mkdir -p "$dst"
        for sub in train val; do
            [ -e "$dst/$sub" ] || ln -s "$(cd "$src/$sub" && pwd)" "$dst/$sub"
        done
        staged=$((staged + 1))
    done
    echo "  linked $staged run(s) into $REPO/local/yolo_dataset/"
else
    echo "  NOTE: no prebuilt YOLO temp datasets at $OLD_TEMP;" >&2
    echo "        eval_sweep.py will refuse to run YOLO shards until they exist." >&2
fi

echo
echo "Done. Verify with: python verify_staged_data.py"
